//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ITS.CompanyBookSystem.DataAccess.Entity
{
    public partial class CompanyBookSystemEntities : DbContext
    {
        public CompanyBookSystemEntities()
            : base("name=CompanyBookSystemEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookObject> BookObject { get; set; }
        public DbSet<BookObjectType> BookObjectType { get; set; }
        public DbSet<BookRecords> BookRecords { get; set; }
        public DbSet<Departments> Departments { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<ObjectStyle> ObjectStyle { get; set; }
    }
}
