//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ITS.CompanyBookSystem.DataAccess.Entity
{
    public partial class Persons
    {
        public Persons()
        {
            this.Events = new HashSet<Events>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid DepartmentId { get; set; }
        public string Location { get; set; }
        public string Describe { get; set; }
        public int State { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual ICollection<Events> Events { get; set; }
    }
    
}
